image: node:10.12.0

stages:
  - build
  - test
  - deploy

heroku-deployment:
    stage: deploy
    script:
     - npm install --production
     - git push https://git.heroku.com/first-express-app-10252018.git master
