image: node:10.12.0

stages:
  - build
  - test
  - deploy

heroku-deployment:
    stage: deploy
    script:
     - npm install --production
     - (echo "machine git.heroku.com"; echo " username shilpa.patwary13@gmail.com"; echo " password $HEROKU_PASSWORD") > ~/.netrc
     - git add . 
     - git commit -m "updating" 
     - git push -f https://git.heroku.com/hello-express-cicd-261018.git master
